
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crewsec?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=False
    username: root
    password: Abde@2001

storage:
  location: /Users/blanzin/Desktop/bucket

token:
  signing:
    key: phdin9WOVV3EJZdJyVvxeXeG3ieE5IH/WlyQBGC7uGk=