
spring:
  datasource:
    url: jdbc:postgres://localhost:5432/crewsec?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=False
    username: compiledideas
    password: compiledideas@27701

storage:
  location: /Users/blanzin/Desktop/bucket

token:
  signing:
    key: phdin9WOVV3EJZdJyVvxeXeG3ieE5IH/WlyQBGC7uGk=