spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crewsec?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=False
    username: compiledIdeas
    password: user_compiledIdeas@27701@SAN$

storage:
  location: /root/bucket

app:
  firebase-configuration-file: crewsec-firebase-admin.json

token:
  signing:
    key: ZpgvK69ofziH64hPyJuysTEmixjVXn7byP1YISwmeSbYiCElZ39E/g==