spring:
  profiles:
    active: dev

  application:
    name: crewsec-backend

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

app:
  firebase-configuration-file: /root/config/crewsec-firebase-admin.json
server:
  port: 8080