name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: |
          export SPRING_PROFILES_ACTIVE=prod
          export SERVER_PORT=8080
          echo "Activating prod profile and setting port to 8080"
          mvn clean package

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-application
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-application
          path: target/

      - name: Setup key
        id: setup-key
        env:
          DEPLOY_KEY: ${{ secrets.SSHKEY }}
        run: |
          echo "$DEPLOY_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem

      - name: Stop Existing Application
        run: |
            # Arrêter l'application si elle est déjà en cours d'exécution via systemd
            sudo systemctl stop springboot-app || true
            echo "Stopped running application (if any)."

      - name: Copy JAR and Create Systemd Service
        run: |
            # Créez le dossier de déploiement si nécessaire
            mkdir -p /home/springboot-app
            # Copiez le JAR généré dans le dossier de déploiement
            cp target/blanzin-back-0.0.1-SNAPSHOT.jar /home/springboot-app/app.jar
            echo "Copied JAR to /home/springboot-app."
            
            # Créez le fichier de service systemd
            echo "[Unit]
            Description=Spring Boot Application
            After=network.target
            
            [Service]
            User=root
            ExecStart=/usr/bin/java -jar -Dspring.profiles.active=prod /home/springboot-app/app.jar
            
            SuccessExitStatus=143
            StandardOutput=journal
            StandardError=journal
            WorkingDirectory=/home/springboot-app
            Restart=always
            
            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/springboot-app.service > /dev/null
            
            # Recharge systemd pour reconnaître le nouveau service
            sudo systemctl daemon-reload

      - name: Start Application as Service
        run: |
          # Démarrez l'application en tant que service
          sudo systemctl start springboot-app
          
          # Activez le démarrage automatique au boot
          sudo systemctl enable springboot-app
          echo "Started application as systemd service."
